### ISSUE TITLE
Change required for Windows OS

### ISSUE THREAD

**Issue by dylanil** [mw281685/IFoA-FL-WP#3]
Commenting here as we'll soon lose the Teams comments:

"
I think I got this to work on Windows actually.
 
In "IFoAserver.py" need to update this section to:

 

And in "IFoA client  [ Multilayer ] [freMTPL2freq].py" this section needs to be:
 
 "

fl.server.start_server(
        server_address="localhost:8080",
        config=fl.server.ServerConfig(num_rounds=10), strategy=strategy"
 
and
 
"fl.client.start_numpy_client(server_address="localhost:8080", client=agent,)"

"

see here for more info: https://github.com/adap/flower/discussions/757#discussioncomment-856931

**Comment by mw281685** [comment]
fixed 99d7ca2 




    system = platform.system()
    if system == "Windows":
        server_address="localhost:8080"
    else:
        server_address= "[::]:8080"


    fl.server.start_server(
        server_address=server_address,
        config=fl.server.ServerConfig(num_rounds=run_config.server_config["num_rounds"]),
        strategy=strategy
    )
