### ISSUE TITLE
EPOCHS_LOCAL_GLOBAL used in client script

### ISSUE THREAD

**Issue by dylanil** [mw281685/IFoA-FL-WP#8]
EPOCHS_LOCAL_GLOBAL used in client script

**Comment by mw281685** [comment]
Agreed. Will remove it as we no longer need to train local model before starting FL training.

**Comment by dylanil** [comment]
I can see it's in the client script so might want to check that

**Comment by mw281685** [comment]
Correct, we currently have local model training for EPOCHS_LOCAL_GLOBAL number of epochs before we ping the server to join the FL training. Will remove that in the final version.

**Comment by mw281685** [comment]
resolved
